import React, { useState } from 'react';
import { Wrench, CheckSquare, Square, AlertTriangle, ShieldCheck, Clock, CheckCircle2, ArrowRight } from 'lucide-react';
import { useTelemetry } from '../context/TelemetryContext';

export const Maintenance = () => {
  const { telemetry } = useTelemetry();

  const [checkedActions, setCheckedActions] = useState({
    1: true,
    2: false,
    3: false,
    4: false
  });

  const toggleAction = (id) => {
    setCheckedActions(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const actionItems = [
    {
      id: 1,
      title: 'Inspect cooling system & radiator fins',
      desc: 'Check radiator airflow path for blockage or thermal seal degradation causing +14% temp rise.',
      priority: 'High',
      timeEstimate: '45 mins'
    },
    {
      id: 2,
      title: 'Check engine lubrication & oil filter',
      desc: 'Verify oil pressure transducer calibration and inspect lubrication lines for minor drop.',
      priority: 'High',
      timeEstimate: '30 mins'
    },
    {
      id: 3,
      title: 'Analyze vibration source & crankshaft bearings',
      desc: 'Perform spectral FFT frequency analysis on secondary harmonic 0.42g vibration peak.',
      priority: 'Medium',
      timeEstimate: '60 mins'
    },
    {
      id: 4,
      title: 'Review fuel injection & EFI map calibration',
      desc: 'Ensure air-fuel mixture compensations are aligned with high-altitude mission parameters.',
      priority: 'Medium',
      timeEstimate: '20 mins'
    }
  ];

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="pb-2 border-b border-cyan-500/20">
        <h2 className="text-2xl font-tech font-bold text-white tracking-wide flex items-center gap-2">
          <Wrench className="w-6 h-6 text-cyan-400" />
          Prescriptive Maintenance Recommendations
        </h2>
        <p className="text-xs text-slate-400 font-subtech mt-0.5">
          Dynamic prescriptive maintenance checklists generated by predictive telemetry inference
        </p>
      </div>

      {/* Priority Banner Card */}
      <div className="p-6 rounded-3xl glass-panel border border-red-500/40 shadow-glow-red space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <span className="px-3 py-1 rounded-full bg-red-500 text-navy-950 font-tech font-bold text-xs">
              HIGH PRIORITY
            </span>
            <span className="text-xs font-mono-code text-red-300">TRIGGER: ELEVATED THERMAL GRADIENT</span>
          </div>

          <div className="flex items-center gap-2 text-xs font-tech text-cyan-400">
            <Clock className="w-4 h-4" />
            Next Scheduled Maintenance: <strong className="text-white text-sm">{telemetry.rulHours} Hours</strong>
          </div>
        </div>

        <h3 className="text-xl font-tech font-bold text-white leading-snug">
          “Inspect cooling system and check for overheating-related issues.”
        </h3>

        <p className="text-xs text-slate-300 leading-relaxed">
          AI diagnosis indicates an 87% probability of piston thermal scuffing if operating continuously above 85°C. Servicing recommended within the next {telemetry.rulHours} flight hours to prevent mission abort.
        </p>
      </div>

      {/* Action Items Checklist */}
      <div className="p-6 rounded-3xl glass-panel border border-cyan-500/20 space-y-4">
        <h3 className="font-tech text-base font-bold text-white flex items-center gap-2">
          <CheckCircle2 className="w-5 h-5 text-cyan-400" />
          RECOMMENDED MAINTENANCE ACTION PLAN
        </h3>

        <div className="space-y-3">
          {actionItems.map((item) => {
            const isChecked = checkedActions[item.id];
            return (
              <div
                key={item.id}
                onClick={() => toggleAction(item.id)}
                className={`p-4 rounded-2xl border cursor-pointer transition-all flex items-start gap-4 ${
                  isChecked
                    ? 'bg-emerald-500/10 border-emerald-500/40 text-emerald-100'
                    : 'bg-navy-950/70 border-cyan-500/20 hover:border-cyan-500/40 text-slate-200'
                }`}
              >
                <button className="mt-0.5 text-cyan-400 focus:outline-none">
                  {isChecked ? (
                    <CheckSquare className="w-5 h-5 text-emerald-400" />
                  ) : (
                    <Square className="w-5 h-5 text-slate-500" />
                  )}
                </button>

                <div className="flex-1 space-y-1">
                  <div className="flex items-center justify-between">
                    <h4 className={`font-tech text-sm font-bold ${isChecked ? 'line-through text-slate-400' : 'text-white'}`}>
                      {item.title}
                    </h4>
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-mono-code text-slate-400">{item.timeEstimate}</span>
                      <span className={`px-2 py-0.5 rounded text-[10px] font-tech ${
                        item.priority === 'High' ? 'bg-red-500/20 text-red-300 border border-red-500/40' : 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                      }`}>
                        {item.priority} Priority
                      </span>
                    </div>
                  </div>
                  <p className="text-xs text-slate-400">{item.desc}</p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
