import React, { useState } from 'react';
import { FileSpreadsheet, Download, Printer, Eye, CheckCircle2, ShieldCheck, Activity, Calendar } from 'lucide-react';
import { useTelemetry } from '../context/TelemetryContext';
import { useAuth } from '../context/AuthContext';

export const Reports = () => {
  const { telemetry } = useTelemetry();
  const { user } = useAuth();

  const [selectedReport, setSelectedReport] = useState('health'); // health | fault | rul | maintenance

  const reportsList = [
    { id: 'health', name: 'Engine Health & Telemetry Summary', date: 'Sept 06, 2026', size: '1.4 MB' },
    { id: 'fault', name: 'AI Fault Classification & SHAP Report', date: 'Sept 06, 2026', size: '2.1 MB' },
    { id: 'rul', name: 'Remaining Useful Life (RUL) Forecast', date: 'Sept 05, 2026', size: '980 KB' },
    { id: 'maintenance', name: 'Prescriptive Maintenance Action Plan', date: 'Sept 04, 2026', size: '1.8 MB' },
  ];

  const handleDownloadPDF = () => {
    window.print();
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-2 border-b border-cyan-500/20">
        <div>
          <h2 className="text-2xl font-tech font-bold text-white tracking-wide flex items-center gap-2">
            <FileSpreadsheet className="w-6 h-6 text-cyan-400" />
            Tactical Aerospace Telemetry & AI Reports
          </h2>
          <p className="text-xs text-slate-400 font-subtech mt-0.5">
            Exportable defense engineering audit reports and predictive health logs
          </p>
        </div>

        <button
          onClick={handleDownloadPDF}
          className="px-5 py-2.5 rounded-2xl bg-gradient-to-r from-electric-bright to-cyan-400 text-navy-950 font-tech font-bold text-xs tracking-wide shadow-glow-cyan hover:brightness-110 transition-all flex items-center gap-2"
        >
          <Download className="w-4 h-4" />
          DOWNLOAD PDF REPORT
        </button>
      </div>

      {/* Report Selection Tabs */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {reportsList.map((rep) => (
          <button
            key={rep.id}
            onClick={() => setSelectedReport(rep.id)}
            className={`p-4 rounded-2xl border text-left transition-all ${
              selectedReport === rep.id
                ? 'bg-cyan-500/20 border-cyan-400 shadow-glow-cyan text-white'
                : 'bg-navy-950/70 border-cyan-500/10 text-slate-400 hover:text-white'
            }`}
          >
            <p className="font-tech text-xs font-bold text-cyan-300 truncate">{rep.name}</p>
            <div className="flex items-center justify-between text-[10px] text-slate-400 mt-2 font-mono-code">
              <span>{rep.date}</span>
              <span>{rep.size}</span>
            </div>
          </button>
        ))}
      </div>

      {/* Report Formatted Document View */}
      <div className="p-8 rounded-3xl glass-panel border border-cyan-500/30 space-y-6 bg-navy-950/90 print:bg-white print:text-black">
        {/* Printable Header */}
        <div className="flex flex-wrap items-center justify-between pb-6 border-b border-cyan-500/20">
          <div>
            <div className="flex items-center gap-2">
              <ShieldCheck className="w-6 h-6 text-cyan-400" />
              <h3 className="font-tech text-xl font-bold text-white tracking-wide">
                DRDO SIH 26054 — DEFENSE TELEMETRY AUDIT REPORT
              </h3>
            </div>
            <p className="text-xs text-slate-400 font-mono-code mt-1">
              REPORT TYPE: {selectedReport.toUpperCase()} AUDIT | AIRCRAFT ID: MALE-UAV-001
            </p>
          </div>

          <div className="text-right text-xs text-slate-300 font-mono-code">
            <p>GENERATED BY: <strong className="text-cyan-300">{user.name}</strong></p>
            <p>DATE: {new Date().toLocaleDateString()}</p>
            <p>CLEARANCE: Level 4 Defense</p>
          </div>
        </div>

        {/* Report Content Body */}
        <div className="space-y-6 text-xs text-slate-200">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 rounded-2xl bg-navy-900 border border-cyan-500/20 font-mono-code">
            <div>
              <span className="text-slate-400 block">Overall Health:</span>
              <strong className="text-cyan-300 text-lg font-tech">{telemetry.healthScore}%</strong>
            </div>
            <div>
              <span className="text-slate-400 block">Operating Hours:</span>
              <strong className="text-white text-lg font-tech">{telemetry.operatingHours} h</strong>
            </div>
            <div>
              <span className="text-slate-400 block">Predicted Fault:</span>
              <strong className="text-amber-300 text-lg font-tech">{telemetry.predictedFault}</strong>
            </div>
            <div>
              <span className="text-slate-400 block">RUL Remaining:</span>
              <strong className="text-emerald-400 text-lg font-tech">{telemetry.rulHours} Hours</strong>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="font-tech text-sm font-bold text-cyan-400 uppercase tracking-wide">
              1. Executive Telemetry Summary
            </h4>
            <p className="leading-relaxed text-slate-300">
              This report provides a formal evaluation of the Aero Piston Engine fitted on MALE UAV-001. Telemetry streams continuously monitored across 8 sensor channels (RPM, Temperature, Oil Pressure, Vibration, Fuel Consumption, Engine Load, Exhaust Temp) indicate nominal operational behavior with an early thermal gradient alert detected at 82°C.
            </p>
          </div>

          <div className="space-y-3">
            <h4 className="font-tech text-sm font-bold text-cyan-400 uppercase tracking-wide">
              2. AI Diagnostics & Root Cause Attribution
            </h4>
            <ul className="list-disc list-inside space-y-1 text-slate-300 font-mono-code">
              <li>Crankcase Temperature elevated by +14% relative to standard flight baseline.</li>
              <li>Piston harmonic vibration amplitude recorded at 0.42g.</li>
              <li>Oil pressure maintained within acceptable safety tolerance (3.8 bar).</li>
              <li>XGBoost anomaly classifier confidence rating: {telemetry.faultProbability}%.</li>
            </ul>
          </div>

          <div className="space-y-3">
            <h4 className="font-tech text-sm font-bold text-cyan-400 uppercase tracking-wide">
              3. Authorized Engineering Recommendations
            </h4>
            <p className="leading-relaxed text-slate-300">
              Action Plan: Complete visual and thermal inspection of cylinder cooling fins within the next {telemetry.rulHours} operating flight hours. Replace lubrication oil filter as part of standard pre-flight protocol.
            </p>
          </div>
        </div>

        {/* Footer Signature */}
        <div className="pt-6 border-t border-cyan-500/20 flex justify-between items-center text-[10px] font-mono-code text-slate-400">
          <span>CLASSIFICATION: RESTRICTED DEFENSE TELEMETRY</span>
          <span>APPROVED BY: ANJALI (AEROSPACE ENGINEER)</span>
        </div>
      </div>
    </div>
  );
};
